### ISSUE TITLE
No entry or class found for 'flash'

### ISSUE THREAD

**Issue by jxmx** [trendschau/typemill#424]
On a clean installation of Typemill 2.0.2, after going through the initial account setup, post-login all I can get is below. The default site contents and everything else seem fine.

```
Slim Application Error

The application could not run because of the following error:
Details
Type: DI\NotFoundException
Code: 0
Message: No entry or class found for 'flash'
File: /var/www/html-dev/tm/system/vendor/php-di/php-di/src/Container.php
Line: 136
Trace

#0 /var/www/html-dev/tm/system/typemill/Controllers/ControllerWebAuth.php(81): DI\Container->get()
#1 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Typemill\Controllers\ControllerWebAuth->login()
#2 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#3 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#4 /var/www/html-dev/tm/system/typemill/Middleware/WebRedirectIfAuthenticated.php(41): Slim\MiddlewareDispatcher->handle()
#5 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Typemill\Middleware\WebRedirectIfAuthenticated->process()
#6 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#7 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#8 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#9 /var/www/html-dev/tm/system/typemill/Middleware/AssetMiddleware.php(38): Slim\Routing\RouteRunner->handle()
#10 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Typemill\Middleware\AssetMiddleware->process()
#11 /var/www/html-dev/tm/system/typemill/Middleware/ValidationErrorsMiddleware.php(35): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#12 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Typemill\Middleware\ValidationErrorsMiddleware->__invoke()
#13 /var/www/html-dev/tm/system/typemill/Middleware/SecurityMiddleware.php(140): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#14 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Typemill\Middleware\securityMiddleware->process()
#15 /var/www/html-dev/tm/system/typemill/Middleware/OldInputMiddleware.php(32): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#16 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Typemill\Middleware\OldInputMiddleware->__invoke()
#17 /var/www/html-dev/tm/system/typemill/Middleware/FlashMessages.php(32): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#18 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Typemill\Middleware\FlashMessages->__invoke()
#19 /var/www/html-dev/tm/system/vendor/slim/twig-view/src/TwigMiddleware.php(115): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#20 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Views\TwigMiddleware->process()
#21 /var/www/html-dev/tm/system/typemill/Middleware/JsonBodyParser.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#22 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Typemill\Middleware\JsonBodyParser->process()
#23 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#24 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#25 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#26 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#27 /var/www/html-dev/tm/system/typemill/Middleware/SessionMiddleware.php(60): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#28 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Typemill\Middleware\SessionMiddleware->process()
#29 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#30 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#31 /var/www/html-dev/tm/system/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#32 /var/www/html-dev/tm/system/typemill/system.php(370): Slim\App->run()
#33 /var/www/html-dev/tm/index.php(5): require('...')
#34 {main}
```

**Comment by jxmx** [comment]
`system/vendor/slim/flash` is provided. Should have mentioned this is unpacking the tarball, not using Git/Symphony.

**Comment by trendschau** [comment]
Sorry, I did not update this, flash is not used anymore so this problem has been fixed long ago
